Encounters can now be created through macros
etriebe/dnd-randomizer pull request #98
Opened 2024-03-26 01:38 UTC by Drejn

Here's a macro example to create an encounter:

dndrandomizer.generateDynamicEncounter("Single BBEG","Treasure Horde","Variety of","deadly",150,300,5);

Here's a macro example that works by triggering a tile using Monk's Tile Trigger. The args passed is the circle radius, while the tile is automatically passed by the module

dndrandomizer.generateDynamicEncounter("Single BBEG","Treasure Horde","Variety of","deadly",tile.x,tile.y,args[0]);

2024-03-27 21:23 UTC, etriebe requested changes

2024-03-27 21:23 UTC, etriebe commented on scripts/encounter.js
> +
Extra newline

2024-03-27 21:23 UTC, etriebe commented on scripts/encounter.js
> +
Extra newline

2024-03-29 01:07 UTC, Drejn commented
let me upload an updated version (i had those changes listed already)

2024-03-29 01:07 UTC, closed without merging